2021-02-16 17:22:52,964 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:22:52,965 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:22:52,967 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,967 main.py:86  INFO Saving collection in database
2021-02-16 17:22:52,969 main.py:60  ERROR User files must be in csv format
2021-02-16 17:22:52,970 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,970 main.py:73  ERROR Users need four parameters
2021-02-16 17:22:52,970 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,970 main.py:73  ERROR Users need four parameters
2021-02-16 17:22:52,971 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,971 main.py:73  ERROR Users need four parameters
2021-02-16 17:22:52,971 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,971 main.py:73  ERROR Users need four parameters
2021-02-16 17:22:52,971 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,971 main.py:73  ERROR Users need four parameters
2021-02-16 17:22:52,973 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,973 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:22:52,973 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,973 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:22:52,973 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,973 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:22:52,973 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:52,973 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:22:52,975 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:52,975 main.py:140 INFO Saving collection in database
2021-02-16 17:22:52,977 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 17:22:52,978 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:52,978 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:22:52,979 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:52,979 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:22:52,979 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:52,979 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:22:52,979 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:52,979 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:22:52,979 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:52,979 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:22:52,981 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:52,981 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:22:52,981 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:52,981 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:22:52,981 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:52,981 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:22:52,982 main.py:159 INFO Adding a new User
2021-02-16 17:22:52,983 main.py:171 INFO Updating an User
2021-02-16 17:22:52,985 main.py:184 INFO Deleting an User
2021-02-16 17:22:52,986 main.py:198 INFO Searching for an User
2021-02-16 17:22:52,987 main.py:198 INFO Searching for an User
2021-02-16 17:22:52,988 main.py:216 INFO Adding an UserStatus
2021-02-16 17:22:52,989 main.py:228 INFO Updating an UserStatus
2021-02-16 17:22:52,991 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:22:52,992 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:22:52,993 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:22:52,994 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:22:53,169 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,169 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:22:53,236 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,236 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:22:53,236 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 17:22:53,236 main.py:159 INFO Adding a new User
2021-02-16 17:22:53,270 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:22:53,270 main.py:159 INFO Adding a new User
2021-02-16 17:22:53,270 users.py:49  ERROR User dave03 already exists
2021-02-16 17:22:53,271 main.py:171 INFO Updating an User
2021-02-16 17:22:53,303 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 17:22:53,304 main.py:171 INFO Updating an User
2021-02-16 17:22:53,304 users.py:61  ERROR User dave02 not found in database
2021-02-16 17:22:53,304 main.py:198 INFO Searching for an User
2021-02-16 17:22:53,304 users.py:93  INFO User dave03 sucessfully found
2021-02-16 17:22:53,304 main.py:198 INFO Searching for an User
2021-02-16 17:22:53,305 users.py:91  ERROR User dave02 not found in database
2021-02-16 17:22:53,305 users.py:21  INFO User None created
2021-02-16 17:22:53,305 main.py:184 INFO Deleting an User
2021-02-16 17:22:53,337 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 17:22:53,337 main.py:184 INFO Deleting an User
2021-02-16 17:22:53,338 users.py:78  ERROR User dave03 not found in database
2021-02-16 17:22:53,338 main.py:159 INFO Adding a new User
2021-02-16 17:22:53,370 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:22:53,370 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:22:53,370 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 17:22:53,370 main.py:216 INFO Adding an UserStatus
2021-02-16 17:22:53,404 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 17:22:53,404 main.py:216 INFO Adding an UserStatus
2021-02-16 17:22:53,405 user_status.py:48  ERROR Status dave03_01 already in database
2021-02-16 17:22:53,405 main.py:228 INFO Updating an UserStatus
2021-02-16 17:22:53,438 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 17:22:53,438 main.py:228 INFO Updating an UserStatus
2021-02-16 17:22:53,439 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 17:22:53,439 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:22:53,439 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 17:22:53,439 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:22:53,440 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 17:22:53,440 user_status.py:20  INFO Status None created
2021-02-16 17:22:53,440 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:22:53,471 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 17:22:53,471 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:22:53,472 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 17:22:53,473 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:22:53,475 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,476 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,477 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 17:22:53,479 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,479 user_status.py:48  ERROR Status rando_001 already in database
2021-02-16 17:22:53,481 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,487 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 17:22:53,488 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,489 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 17:22:53,490 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,490 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 17:22:53,492 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,492 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 17:22:53,493 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,494 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 17:22:53,510 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:22:53,511 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 17:22:53,511 user_status.py:20  INFO Status None created
2021-02-16 17:22:53,512 users.py:21  INFO User rando created
2021-02-16 17:22:53,513 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,514 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,515 users.py:51  INFO User rando sucessfully added
2021-02-16 17:22:53,516 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,517 users.py:49  ERROR User rando already exists
2021-02-16 17:22:53,518 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,519 users.py:68  INFO User rando sucessfully modified
2021-02-16 17:22:53,521 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,521 users.py:61  ERROR User rando not found in database
2021-02-16 17:22:53,522 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,523 users.py:81  INFO User rando sucessfully deleted
2021-02-16 17:22:53,524 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,524 users.py:78  ERROR User rando not found in database
2021-02-16 17:22:53,525 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,526 users.py:93  INFO User rando sucessfully found
2021-02-16 17:22:53,530 users.py:33  INFO New UserCollection instance created
2021-02-16 17:22:53,530 users.py:91  ERROR User rando not found in database
2021-02-16 17:22:53,530 users.py:21  INFO User None created
2021-02-16 17:23:38,329 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:23:38,330 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:23:38,332 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,332 main.py:86  INFO Saving collection in database
2021-02-16 17:23:38,334 main.py:60  ERROR User files must be in csv format
2021-02-16 17:23:38,335 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,335 main.py:73  ERROR Users need four parameters
2021-02-16 17:23:38,336 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,336 main.py:73  ERROR Users need four parameters
2021-02-16 17:23:38,336 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,336 main.py:73  ERROR Users need four parameters
2021-02-16 17:23:38,336 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,336 main.py:73  ERROR Users need four parameters
2021-02-16 17:23:38,336 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,336 main.py:73  ERROR Users need four parameters
2021-02-16 17:23:38,338 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,338 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:23:38,338 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,338 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:23:38,338 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,338 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:23:38,339 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,339 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:23:38,340 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,340 main.py:140 INFO Saving collection in database
2021-02-16 17:23:38,342 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 17:23:38,344 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,344 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:23:38,344 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,344 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:23:38,344 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,345 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:23:38,345 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,345 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:23:38,345 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,345 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:23:38,346 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,346 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:23:38,347 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,347 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:23:38,347 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,347 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:23:38,348 main.py:159 INFO Adding a new User
2021-02-16 17:23:38,349 main.py:171 INFO Updating an User
2021-02-16 17:23:38,350 main.py:184 INFO Deleting an User
2021-02-16 17:23:38,352 main.py:198 INFO Searching for an User
2021-02-16 17:23:38,353 main.py:198 INFO Searching for an User
2021-02-16 17:23:38,354 main.py:216 INFO Adding an UserStatus
2021-02-16 17:23:38,355 main.py:228 INFO Updating an UserStatus
2021-02-16 17:23:38,356 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:23:38,358 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:23:38,359 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:23:38,360 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:23:38,413 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,413 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:23:38,480 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,480 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:23:38,480 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 17:23:38,481 main.py:159 INFO Adding a new User
2021-02-16 17:23:38,514 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:23:38,514 main.py:159 INFO Adding a new User
2021-02-16 17:23:38,515 users.py:49  ERROR User dave03 already exists
2021-02-16 17:23:38,515 main.py:171 INFO Updating an User
2021-02-16 17:23:38,547 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 17:23:38,547 main.py:171 INFO Updating an User
2021-02-16 17:23:38,548 users.py:61  ERROR User dave02 not found in database
2021-02-16 17:23:38,548 main.py:198 INFO Searching for an User
2021-02-16 17:23:38,548 users.py:93  INFO User dave03 sucessfully found
2021-02-16 17:23:38,548 main.py:198 INFO Searching for an User
2021-02-16 17:23:38,549 users.py:91  ERROR User dave02 not found in database
2021-02-16 17:23:38,549 users.py:21  INFO User None created
2021-02-16 17:23:38,549 main.py:184 INFO Deleting an User
2021-02-16 17:23:38,581 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 17:23:38,581 main.py:184 INFO Deleting an User
2021-02-16 17:23:38,582 users.py:78  ERROR User dave03 not found in database
2021-02-16 17:23:38,582 main.py:159 INFO Adding a new User
2021-02-16 17:23:38,615 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:23:38,615 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:23:38,616 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 17:23:38,616 main.py:216 INFO Adding an UserStatus
2021-02-16 17:23:38,649 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 17:23:38,649 main.py:216 INFO Adding an UserStatus
2021-02-16 17:23:38,650 user_status.py:48  ERROR Status dave03_01 already in database
2021-02-16 17:23:38,650 main.py:228 INFO Updating an UserStatus
2021-02-16 17:23:38,682 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 17:23:38,682 main.py:228 INFO Updating an UserStatus
2021-02-16 17:23:38,683 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 17:23:38,683 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:23:38,683 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 17:23:38,684 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:23:38,684 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 17:23:38,684 user_status.py:20  INFO Status None created
2021-02-16 17:23:38,684 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:23:38,716 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 17:23:38,716 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:23:38,717 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 17:23:38,718 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:23:38,720 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,727 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,728 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 17:23:38,729 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,730 user_status.py:48  ERROR Status rando_001 already in database
2021-02-16 17:23:38,731 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,732 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 17:23:38,733 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,734 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 17:23:38,736 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,736 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 17:23:38,737 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,738 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 17:23:38,739 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,740 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 17:23:38,756 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:23:38,756 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 17:23:38,756 user_status.py:20  INFO Status None created
2021-02-16 17:23:38,757 users.py:21  INFO User rando created
2021-02-16 17:23:38,759 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,760 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,761 users.py:51  INFO User rando sucessfully added
2021-02-16 17:23:38,762 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,763 users.py:49  ERROR User rando already exists
2021-02-16 17:23:38,764 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,765 users.py:68  INFO User rando sucessfully modified
2021-02-16 17:23:38,766 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,767 users.py:61  ERROR User rando not found in database
2021-02-16 17:23:38,768 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,768 users.py:81  INFO User rando sucessfully deleted
2021-02-16 17:23:38,770 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,770 users.py:78  ERROR User rando not found in database
2021-02-16 17:23:38,771 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,772 users.py:93  INFO User rando sucessfully found
2021-02-16 17:23:38,777 users.py:33  INFO New UserCollection instance created
2021-02-16 17:23:38,777 users.py:91  ERROR User rando not found in database
2021-02-16 17:23:38,777 users.py:21  INFO User None created
2021-02-16 17:25:27,078 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:25:27,145 users.py:33  INFO New UserCollection instance created
2021-02-16 17:25:27,145 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:25:27,212 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:25:42,738 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:25:42,744 main.py:86  INFO Saving collection in database
2021-02-16 17:26:37,329 main.py:198 INFO Searching for an User
2021-02-16 17:28:09,818 users.py:93  INFO User Luz.Ozzy15 sucessfully found
2021-02-16 17:56:26,821 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:56:26,823 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:56:26,825 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,825 main.py:86  INFO Saving collection in database
2021-02-16 17:56:26,827 main.py:60  ERROR User files must be in csv format
2021-02-16 17:56:26,828 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,829 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:26,829 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,829 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:26,829 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,829 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:26,829 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,829 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:26,829 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,830 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:26,831 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,831 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:56:26,831 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,831 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:56:26,831 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,831 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:56:26,832 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,832 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:56:26,833 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:26,833 main.py:140 INFO Saving collection in database
2021-02-16 17:56:26,835 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 17:56:26,836 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:26,836 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:26,837 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:26,837 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:26,837 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:26,837 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:26,837 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:26,837 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:26,837 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:26,837 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:26,839 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:26,839 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:56:26,839 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:26,839 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:56:26,839 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:26,839 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:56:26,840 main.py:159 INFO Adding a new User
2021-02-16 17:56:26,842 main.py:171 INFO Updating an User
2021-02-16 17:56:26,843 main.py:184 INFO Deleting an User
2021-02-16 17:56:26,844 main.py:198 INFO Searching for an User
2021-02-16 17:56:26,845 main.py:198 INFO Searching for an User
2021-02-16 17:56:26,847 main.py:216 INFO Adding an UserStatus
2021-02-16 17:56:26,848 main.py:228 INFO Updating an UserStatus
2021-02-16 17:56:26,849 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:56:26,850 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:56:26,851 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:56:26,852 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:56:26,902 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:26,903 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:56:26,969 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:26,970 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:26,970 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 17:56:26,970 main.py:159 INFO Adding a new User
2021-02-16 17:56:27,003 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:56:27,004 main.py:159 INFO Adding a new User
2021-02-16 17:56:27,004 users.py:49  ERROR User dave03 already exists
2021-02-16 17:56:27,004 main.py:171 INFO Updating an User
2021-02-16 17:56:27,037 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 17:56:27,037 main.py:171 INFO Updating an User
2021-02-16 17:56:27,038 users.py:61  ERROR User dave02 not found in database
2021-02-16 17:56:27,038 main.py:198 INFO Searching for an User
2021-02-16 17:56:27,038 users.py:93  INFO User dave03 sucessfully found
2021-02-16 17:56:27,038 main.py:198 INFO Searching for an User
2021-02-16 17:56:27,039 users.py:91  ERROR User dave02 not found in database
2021-02-16 17:56:27,039 main.py:184 INFO Deleting an User
2021-02-16 17:56:27,071 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 17:56:27,071 main.py:184 INFO Deleting an User
2021-02-16 17:56:27,071 users.py:78  ERROR User dave03 not found in database
2021-02-16 17:56:27,071 main.py:159 INFO Adding a new User
2021-02-16 17:56:27,104 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:56:27,105 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:27,105 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 17:56:27,105 main.py:216 INFO Adding an UserStatus
2021-02-16 17:56:27,138 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 17:56:27,138 main.py:216 INFO Adding an UserStatus
2021-02-16 17:56:27,138 user_status.py:48  ERROR Status dave03_01 already in database
2021-02-16 17:56:27,138 main.py:228 INFO Updating an UserStatus
2021-02-16 17:56:27,172 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 17:56:27,172 main.py:228 INFO Updating an UserStatus
2021-02-16 17:56:27,172 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 17:56:27,172 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:56:27,173 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 17:56:27,173 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:56:27,174 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 17:56:27,174 user_status.py:20  INFO Status None created
2021-02-16 17:56:27,174 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:56:27,205 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 17:56:27,205 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:56:27,206 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 17:56:27,207 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:56:27,209 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:27,212 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:27,217 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 17:56:27,219 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:27,220 user_status.py:48  ERROR Status rando_001 already in database
2021-02-16 17:56:27,221 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:27,222 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 17:56:27,223 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:27,223 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 17:56:27,225 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:27,226 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 17:56:27,227 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:27,227 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 17:56:27,229 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:27,229 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 17:56:27,245 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:27,245 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 17:56:27,245 user_status.py:20  INFO Status None created
2021-02-16 17:56:27,246 users.py:21  INFO User rando created
2021-02-16 17:56:27,247 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:27,249 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:27,250 users.py:51  INFO User rando sucessfully added
2021-02-16 17:56:27,251 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:27,252 users.py:49  ERROR User rando already exists
2021-02-16 17:56:27,253 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:27,254 users.py:68  INFO User rando sucessfully modified
2021-02-16 17:56:27,255 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:27,255 users.py:61  ERROR User rando not found in database
2021-02-16 17:56:27,257 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:27,257 users.py:81  INFO User rando sucessfully deleted
2021-02-16 17:56:27,258 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:27,259 users.py:78  ERROR User rando not found in database
2021-02-16 17:56:27,260 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:27,261 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='2185415890120'> sucessfully found
2021-02-16 17:56:27,262 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:27,262 users.py:91  ERROR User rando not found in database
2021-02-16 17:56:31,005 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:56:31,006 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:56:31,007 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,007 main.py:86  INFO Saving collection in database
2021-02-16 17:56:31,009 main.py:60  ERROR User files must be in csv format
2021-02-16 17:56:31,011 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,011 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:31,011 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,011 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:31,011 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,011 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:31,011 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,012 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:31,012 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,012 main.py:73  ERROR Users need four parameters
2021-02-16 17:56:31,013 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,013 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:56:31,013 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,013 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:56:31,014 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,014 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:56:31,014 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,014 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:56:31,015 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,015 main.py:140 INFO Saving collection in database
2021-02-16 17:56:31,018 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 17:56:31,019 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,019 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:31,019 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,019 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:31,019 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,019 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:31,020 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,020 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:31,020 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,020 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:56:31,021 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,021 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:56:31,021 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,022 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:56:31,022 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,022 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:56:31,023 main.py:159 INFO Adding a new User
2021-02-16 17:56:31,024 main.py:171 INFO Updating an User
2021-02-16 17:56:31,025 main.py:184 INFO Deleting an User
2021-02-16 17:56:31,026 main.py:198 INFO Searching for an User
2021-02-16 17:56:31,028 main.py:198 INFO Searching for an User
2021-02-16 17:56:31,029 main.py:216 INFO Adding an UserStatus
2021-02-16 17:56:31,030 main.py:228 INFO Updating an UserStatus
2021-02-16 17:56:31,031 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:56:31,032 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:56:31,034 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:56:31,035 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:56:31,084 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,084 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:56:31,152 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,152 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:56:31,152 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 17:56:31,152 main.py:159 INFO Adding a new User
2021-02-16 17:56:31,185 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:56:31,186 main.py:159 INFO Adding a new User
2021-02-16 17:56:31,186 users.py:49  ERROR User dave03 already exists
2021-02-16 17:56:31,186 main.py:171 INFO Updating an User
2021-02-16 17:56:31,219 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 17:56:31,219 main.py:171 INFO Updating an User
2021-02-16 17:56:31,220 users.py:61  ERROR User dave02 not found in database
2021-02-16 17:56:31,220 main.py:198 INFO Searching for an User
2021-02-16 17:56:31,220 users.py:93  INFO User dave03 sucessfully found
2021-02-16 17:56:31,220 main.py:198 INFO Searching for an User
2021-02-16 17:56:31,221 users.py:91  ERROR User dave02 not found in database
2021-02-16 17:56:31,221 main.py:184 INFO Deleting an User
2021-02-16 17:56:31,252 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 17:56:31,252 main.py:184 INFO Deleting an User
2021-02-16 17:56:31,253 users.py:78  ERROR User dave03 not found in database
2021-02-16 17:56:31,253 main.py:159 INFO Adding a new User
2021-02-16 17:56:31,286 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:56:31,286 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:56:31,286 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 17:56:31,286 main.py:216 INFO Adding an UserStatus
2021-02-16 17:56:31,320 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 17:56:31,320 main.py:216 INFO Adding an UserStatus
2021-02-16 17:56:31,320 user_status.py:48  ERROR Status dave03_01 already in database
2021-02-16 17:56:31,321 main.py:228 INFO Updating an UserStatus
2021-02-16 17:56:31,353 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 17:56:31,353 main.py:228 INFO Updating an UserStatus
2021-02-16 17:56:31,354 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 17:56:31,354 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:56:31,354 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 17:56:31,355 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:56:31,355 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 17:56:31,355 user_status.py:20  INFO Status None created
2021-02-16 17:56:31,355 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:56:31,387 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 17:56:31,387 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:56:31,388 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 17:56:31,389 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:56:31,391 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,393 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,394 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 17:56:31,395 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,396 user_status.py:48  ERROR Status rando_001 already in database
2021-02-16 17:56:31,398 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,404 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 17:56:31,405 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,406 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 17:56:31,407 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,408 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 17:56:31,409 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,409 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 17:56:31,410 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,411 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 17:56:31,428 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:56:31,428 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 17:56:31,428 user_status.py:20  INFO Status None created
2021-02-16 17:56:31,429 users.py:21  INFO User rando created
2021-02-16 17:56:31,431 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,432 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,433 users.py:51  INFO User rando sucessfully added
2021-02-16 17:56:31,434 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,435 users.py:49  ERROR User rando already exists
2021-02-16 17:56:31,436 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,437 users.py:68  INFO User rando sucessfully modified
2021-02-16 17:56:31,438 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,439 users.py:61  ERROR User rando not found in database
2021-02-16 17:56:31,440 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,440 users.py:81  INFO User rando sucessfully deleted
2021-02-16 17:56:31,441 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,442 users.py:78  ERROR User rando not found in database
2021-02-16 17:56:31,443 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,443 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='1593054063624'> sucessfully found
2021-02-16 17:56:31,445 users.py:33  INFO New UserCollection instance created
2021-02-16 17:56:31,445 users.py:91  ERROR User rando not found in database
2021-02-16 17:57:24,560 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:57:24,561 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:57:24,563 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,563 main.py:86  INFO Saving collection in database
2021-02-16 17:57:24,565 main.py:60  ERROR User files must be in csv format
2021-02-16 17:57:24,566 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,566 main.py:73  ERROR Users need four parameters
2021-02-16 17:57:24,566 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,566 main.py:73  ERROR Users need four parameters
2021-02-16 17:57:24,567 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,567 main.py:73  ERROR Users need four parameters
2021-02-16 17:57:24,567 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,567 main.py:73  ERROR Users need four parameters
2021-02-16 17:57:24,567 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,567 main.py:73  ERROR Users need four parameters
2021-02-16 17:57:24,569 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,569 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:57:24,569 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,569 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:57:24,569 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,569 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:57:24,569 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,569 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:57:24,571 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,571 main.py:140 INFO Saving collection in database
2021-02-16 17:57:24,573 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 17:57:24,574 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,574 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:57:24,575 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,575 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:57:24,575 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,575 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:57:24,575 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,575 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:57:24,575 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,575 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:57:24,577 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,577 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:57:24,577 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,577 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:57:24,577 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,577 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:57:24,578 main.py:159 INFO Adding a new User
2021-02-16 17:57:24,579 main.py:171 INFO Updating an User
2021-02-16 17:57:24,581 main.py:184 INFO Deleting an User
2021-02-16 17:57:24,582 main.py:198 INFO Searching for an User
2021-02-16 17:57:24,583 main.py:198 INFO Searching for an User
2021-02-16 17:57:24,584 main.py:216 INFO Adding an UserStatus
2021-02-16 17:57:24,585 main.py:228 INFO Updating an UserStatus
2021-02-16 17:57:24,587 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:57:24,588 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:57:24,589 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:57:24,591 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:57:24,658 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:24,658 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:57:24,725 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,725 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:57:24,725 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 17:57:24,725 main.py:159 INFO Adding a new User
2021-02-16 17:57:24,758 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:57:24,759 main.py:159 INFO Adding a new User
2021-02-16 17:57:24,759 users.py:49  ERROR User dave03 already exists
2021-02-16 17:57:24,759 main.py:171 INFO Updating an User
2021-02-16 17:57:24,792 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 17:57:24,792 main.py:171 INFO Updating an User
2021-02-16 17:57:24,793 users.py:61  ERROR User dave02 not found in database
2021-02-16 17:57:24,793 main.py:198 INFO Searching for an User
2021-02-16 17:57:24,793 users.py:93  INFO User dave03 sucessfully found
2021-02-16 17:57:24,793 main.py:198 INFO Searching for an User
2021-02-16 17:57:24,794 users.py:91  ERROR User dave02 not found in database
2021-02-16 17:57:24,794 main.py:184 INFO Deleting an User
2021-02-16 17:57:24,826 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 17:57:24,826 main.py:184 INFO Deleting an User
2021-02-16 17:57:24,827 users.py:78  ERROR User dave03 not found in database
2021-02-16 17:57:24,827 main.py:159 INFO Adding a new User
2021-02-16 17:57:24,859 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:57:24,860 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:57:24,860 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 17:57:24,860 main.py:216 INFO Adding an UserStatus
2021-02-16 17:57:24,893 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 17:57:24,893 main.py:216 INFO Adding an UserStatus
2021-02-16 17:57:24,894 user_status.py:48  ERROR Status dave03_01 already in database
2021-02-16 17:57:24,894 main.py:228 INFO Updating an UserStatus
2021-02-16 17:57:24,927 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 17:57:24,927 main.py:228 INFO Updating an UserStatus
2021-02-16 17:57:24,927 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 17:57:24,928 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:57:24,928 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 17:57:24,928 user_status.py:20  INFO Status dave03_01 created
2021-02-16 17:57:24,928 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:57:24,929 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 17:57:24,929 user_status.py:20  INFO Status None created
2021-02-16 17:57:24,929 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:57:24,961 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 17:57:24,961 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:57:24,961 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 17:57:24,962 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:57:24,964 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,965 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,966 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 17:57:24,968 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,969 user_status.py:48  ERROR Status rando_001 already in database
2021-02-16 17:57:24,971 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,976 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 17:57:24,977 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,978 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 17:57:24,979 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,980 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 17:57:24,981 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,981 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 17:57:24,983 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,983 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 17:57:24,983 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:57:24,984 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:57:24,985 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 17:57:24,985 user_status.py:20  INFO Status None created
2021-02-16 17:57:24,986 users.py:21  INFO User rando created
2021-02-16 17:57:24,988 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:24,989 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:24,990 users.py:51  INFO User rando sucessfully added
2021-02-16 17:57:24,991 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:24,992 users.py:49  ERROR User rando already exists
2021-02-16 17:57:24,993 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:24,994 users.py:68  INFO User rando sucessfully modified
2021-02-16 17:57:24,995 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:24,995 users.py:61  ERROR User rando not found in database
2021-02-16 17:57:24,997 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:24,998 users.py:81  INFO User rando sucessfully deleted
2021-02-16 17:57:24,999 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:24,999 users.py:78  ERROR User rando not found in database
2021-02-16 17:57:25,001 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:25,001 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='2248754816392'> sucessfully found
2021-02-16 17:57:25,002 users.py:33  INFO New UserCollection instance created
2021-02-16 17:57:25,003 users.py:91  ERROR User rando not found in database
2021-02-16 17:58:42,906 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:58:42,907 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:58:42,909 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,909 main.py:86  INFO Saving collection in database
2021-02-16 17:58:42,911 main.py:60  ERROR User files must be in csv format
2021-02-16 17:58:42,913 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,913 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:42,913 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,913 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:42,913 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,913 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:42,913 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,914 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:42,914 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,914 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:42,915 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,915 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:58:42,915 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,915 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:58:42,916 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,916 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:58:42,916 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:42,916 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:58:42,917 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:42,917 main.py:140 INFO Saving collection in database
2021-02-16 17:58:42,919 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 17:58:42,920 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:42,921 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:42,921 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:42,921 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:42,921 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:42,921 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:42,921 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:42,921 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:42,922 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:42,922 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:42,923 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:42,923 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:58:42,923 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:42,923 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:58:42,923 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:42,924 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:58:42,925 main.py:159 INFO Adding a new User
2021-02-16 17:58:42,926 main.py:171 INFO Updating an User
2021-02-16 17:58:42,927 main.py:184 INFO Deleting an User
2021-02-16 17:58:42,929 main.py:198 INFO Searching for an User
2021-02-16 17:58:42,930 main.py:198 INFO Searching for an User
2021-02-16 17:58:42,931 main.py:216 INFO Adding an UserStatus
2021-02-16 17:58:42,932 main.py:228 INFO Updating an UserStatus
2021-02-16 17:58:42,933 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:58:42,934 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:58:42,935 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:58:42,937 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:58:42,991 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:42,991 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:58:43,058 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,058 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:43,058 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 17:58:43,058 main.py:159 INFO Adding a new User
2021-02-16 17:58:43,092 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:58:43,092 main.py:159 INFO Adding a new User
2021-02-16 17:58:43,092 users.py:49  ERROR User dave03 already exists
2021-02-16 17:58:43,092 main.py:171 INFO Updating an User
2021-02-16 17:58:43,125 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 17:58:43,125 main.py:171 INFO Updating an User
2021-02-16 17:58:43,126 users.py:61  ERROR User dave02 not found in database
2021-02-16 17:58:43,126 main.py:198 INFO Searching for an User
2021-02-16 17:58:43,126 users.py:93  INFO User dave03 sucessfully found
2021-02-16 17:58:43,126 main.py:198 INFO Searching for an User
2021-02-16 17:58:43,127 users.py:91  ERROR User dave02 not found in database
2021-02-16 17:58:43,127 main.py:184 INFO Deleting an User
2021-02-16 17:58:43,159 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 17:58:43,159 main.py:184 INFO Deleting an User
2021-02-16 17:58:43,160 users.py:78  ERROR User dave03 not found in database
2021-02-16 17:58:43,160 main.py:159 INFO Adding a new User
2021-02-16 17:58:43,193 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:58:43,193 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:43,193 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 17:58:43,193 main.py:216 INFO Adding an UserStatus
2021-02-16 17:58:43,226 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 17:58:43,227 main.py:216 INFO Adding an UserStatus
2021-02-16 17:58:43,227 user_status.py:48  ERROR Status dave03_01 already in database
2021-02-16 17:58:43,227 main.py:228 INFO Updating an UserStatus
2021-02-16 17:58:43,260 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 17:58:43,260 main.py:228 INFO Updating an UserStatus
2021-02-16 17:58:43,261 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 17:58:43,261 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:58:43,261 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 17:58:43,262 user_status.py:20  INFO Status dave03_01 created
2021-02-16 17:58:43,262 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:58:43,262 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 17:58:43,263 user_status.py:20  INFO Status None created
2021-02-16 17:58:43,263 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:58:43,294 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 17:58:43,294 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:58:43,295 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 17:58:43,296 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:58:43,297 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,299 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,305 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 17:58:43,307 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,307 user_status.py:48  ERROR Status rando_001 already in database
2021-02-16 17:58:43,309 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,309 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 17:58:43,311 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,311 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 17:58:43,312 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,313 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 17:58:43,315 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,315 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 17:58:43,316 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,317 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 17:58:43,317 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:58:43,318 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:43,318 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 17:58:43,319 user_status.py:20  INFO Status None created
2021-02-16 17:58:43,320 users.py:21  INFO User rando created
2021-02-16 17:58:43,321 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:43,322 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:43,323 users.py:51  INFO User rando sucessfully added
2021-02-16 17:58:43,324 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:43,325 users.py:49  ERROR User rando already exists
2021-02-16 17:58:43,326 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:43,327 users.py:68  INFO User rando sucessfully modified
2021-02-16 17:58:43,328 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:43,329 users.py:61  ERROR User rando not found in database
2021-02-16 17:58:43,330 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:43,330 users.py:81  INFO User rando sucessfully deleted
2021-02-16 17:58:43,331 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:43,332 users.py:78  ERROR User rando not found in database
2021-02-16 17:58:43,333 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:43,333 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='2359248463496'> sucessfully found
2021-02-16 17:58:43,335 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:43,336 users.py:91  ERROR User rando not found in database
2021-02-16 17:58:55,097 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:58:55,099 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:58:55,101 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,101 main.py:86  INFO Saving collection in database
2021-02-16 17:58:55,104 main.py:60  ERROR User files must be in csv format
2021-02-16 17:58:55,106 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,106 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:55,106 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,106 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:55,106 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,106 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:55,106 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,107 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:55,107 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,107 main.py:73  ERROR Users need four parameters
2021-02-16 17:58:55,109 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,109 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:58:55,109 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,109 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:58:55,109 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,109 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:58:55,110 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,110 main.py:78  ERROR Users can not have empty fields
2021-02-16 17:58:55,111 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,112 main.py:140 INFO Saving collection in database
2021-02-16 17:58:55,115 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 17:58:55,116 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,116 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:55,117 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,117 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:55,117 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,117 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:55,117 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,117 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:55,118 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,118 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 17:58:55,119 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,119 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:58:55,120 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,120 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:58:55,120 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,120 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 17:58:55,122 main.py:159 INFO Adding a new User
2021-02-16 17:58:55,123 main.py:171 INFO Updating an User
2021-02-16 17:58:55,125 main.py:184 INFO Deleting an User
2021-02-16 17:58:55,127 main.py:198 INFO Searching for an User
2021-02-16 17:58:55,128 main.py:198 INFO Searching for an User
2021-02-16 17:58:55,130 main.py:216 INFO Adding an UserStatus
2021-02-16 17:58:55,132 main.py:228 INFO Updating an UserStatus
2021-02-16 17:58:55,133 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:58:55,135 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:58:55,137 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:58:55,139 main.py:28  INFO Creating a new UserCollection
2021-02-16 17:58:55,206 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,206 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 17:58:55,272 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,273 main.py:63  INFO Loading users from accounts.csv
2021-02-16 17:58:55,273 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 17:58:55,273 main.py:159 INFO Adding a new User
2021-02-16 17:58:55,306 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:58:55,306 main.py:159 INFO Adding a new User
2021-02-16 17:58:55,307 users.py:49  ERROR User dave03 already exists
2021-02-16 17:58:55,307 main.py:171 INFO Updating an User
2021-02-16 17:58:55,339 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 17:58:55,340 main.py:171 INFO Updating an User
2021-02-16 17:58:55,340 users.py:61  ERROR User dave02 not found in database
2021-02-16 17:58:55,341 main.py:198 INFO Searching for an User
2021-02-16 17:58:55,341 users.py:93  INFO User dave03 sucessfully found
2021-02-16 17:58:55,341 main.py:198 INFO Searching for an User
2021-02-16 17:58:55,342 users.py:91  ERROR User dave02 not found in database
2021-02-16 17:58:55,342 main.py:184 INFO Deleting an User
2021-02-16 17:58:55,373 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 17:58:55,373 main.py:184 INFO Deleting an User
2021-02-16 17:58:55,374 users.py:78  ERROR User dave03 not found in database
2021-02-16 17:58:55,374 main.py:159 INFO Adding a new User
2021-02-16 17:58:55,407 users.py:51  INFO User dave03 sucessfully added
2021-02-16 17:58:55,407 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 17:58:55,407 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 17:58:55,408 main.py:216 INFO Adding an UserStatus
2021-02-16 17:58:55,441 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 17:58:55,441 main.py:216 INFO Adding an UserStatus
2021-02-16 17:58:55,441 user_status.py:48  ERROR Status dave03_01 already in database
2021-02-16 17:58:55,442 main.py:228 INFO Updating an UserStatus
2021-02-16 17:58:55,475 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 17:58:55,475 main.py:228 INFO Updating an UserStatus
2021-02-16 17:58:55,476 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 17:58:55,476 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:58:55,477 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 17:58:55,477 user_status.py:20  INFO Status dave03_01 created
2021-02-16 17:58:55,478 main.py:253 INFO Searching for an UserStatus
2021-02-16 17:58:55,478 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 17:58:55,478 user_status.py:20  INFO Status None created
2021-02-16 17:58:55,479 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:58:55,508 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 17:58:55,509 main.py:240 INFO Deleting an UserStatus
2021-02-16 17:58:55,509 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 17:58:55,511 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:58:55,513 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,515 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,517 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 17:58:55,518 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,520 user_status.py:48  ERROR Status rando_001 already in database
2021-02-16 17:58:55,521 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,523 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 17:58:55,525 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,525 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 17:58:55,527 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,528 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 17:58:55,530 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,530 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 17:58:55,532 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,533 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 17:58:55,533 user_status.py:20  INFO Status rando_001 created
2021-02-16 17:58:55,534 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 17:58:55,535 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 17:58:55,535 user_status.py:20  INFO Status None created
2021-02-16 17:58:55,537 users.py:21  INFO User rando created
2021-02-16 17:58:55,539 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,540 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,542 users.py:51  INFO User rando sucessfully added
2021-02-16 17:58:55,543 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,544 users.py:49  ERROR User rando already exists
2021-02-16 17:58:55,546 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,547 users.py:68  INFO User rando sucessfully modified
2021-02-16 17:58:55,549 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,550 users.py:61  ERROR User rando not found in database
2021-02-16 17:58:55,552 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,552 users.py:81  INFO User rando sucessfully deleted
2021-02-16 17:58:55,554 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,555 users.py:78  ERROR User rando not found in database
2021-02-16 17:58:55,556 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,557 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='1534179574536'> sucessfully found
2021-02-16 17:58:55,558 users.py:33  INFO New UserCollection instance created
2021-02-16 17:58:55,559 users.py:91  ERROR User rando not found in database
2021-02-16 18:01:35,192 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:01:35,687 users.py:33  INFO New UserCollection instance created
2021-02-16 18:01:35,687 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:01:35,754 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:02:11,892 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:02:11,895 main.py:86  INFO Saving collection in database
2021-02-16 18:02:59,530 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:02:59,720 main.py:140 INFO Saving collection in database
2021-02-16 18:05:00,284 main.py:184 INFO Deleting an User
2021-02-16 18:05:00,800 users.py:81  INFO User Bird.Fanchet5 sucessfully deleted
2021-02-16 18:07:26,027 main.py:159 INFO Adding a new User
2021-02-16 18:07:26,028 users.py:49  ERROR User A.Really>lonhg>name_and_I-mean;;just0rediculus,imnotgoing_to=stop1234567890 already exists
2021-02-16 18:08:11,499 main.py:159 INFO Adding a new User
2021-02-16 18:08:11,548 users.py:51  INFO User 1234 sucessfully added
2021-02-16 18:11:44,186 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:11:44,600 users.py:33  INFO New UserCollection instance created
2021-02-16 18:11:44,600 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:11:44,667 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:11:57,294 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:11:57,296 main.py:86  INFO Saving collection in database
2021-02-16 18:12:20,358 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:12:20,535 main.py:140 INFO Saving collection in database
2021-02-16 18:13:09,862 main.py:159 INFO Adding a new User
2021-02-16 18:13:09,863 users.py:49  ERROR User normal_id already exists
2021-02-16 18:13:59,721 main.py:159 INFO Adding a new User
2021-02-16 18:14:00,211 users.py:51  INFO User q sucessfully added
2021-02-16 18:21:47,514 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:21:47,625 users.py:33  INFO New UserCollection instance created
2021-02-16 18:21:47,625 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:21:47,692 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:22:24,517 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:22:24,936 users.py:33  INFO New UserCollection instance created
2021-02-16 18:22:24,936 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:22:25,002 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:22:33,098 main.py:159 INFO Adding a new User
2021-02-16 18:22:33,237 users.py:51  INFO User 1 sucessfully added
2021-02-16 18:22:43,768 main.py:159 INFO Adding a new User
2021-02-16 18:24:40,803 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:24:41,303 users.py:33  INFO New UserCollection instance created
2021-02-16 18:24:41,303 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:24:41,370 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:25:01,481 main.py:159 INFO Adding a new User
2021-02-16 18:27:12,121 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:27:12,559 users.py:33  INFO New UserCollection instance created
2021-02-16 18:27:12,559 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:27:12,626 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:27:19,183 main.py:198 INFO Searching for an User
2021-02-16 18:27:19,184 users.py:91  ERROR User asdf not found in database
2021-02-16 18:27:26,327 main.py:253 INFO Searching for an UserStatus
2021-02-16 18:27:26,328 user_status.py:92  ERROR Status asdf not found database
2021-02-16 18:27:26,328 user_status.py:20  INFO Status None created
2021-02-16 18:29:43,667 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:29:43,669 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:29:43,670 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,670 main.py:86  INFO Saving collection in database
2021-02-16 18:29:43,673 main.py:60  ERROR User files must be in csv format
2021-02-16 18:29:43,674 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,674 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:43,674 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,674 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:43,674 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,674 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:43,675 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,675 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:43,675 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,675 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:43,676 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,676 main.py:78  ERROR Users can not have empty fields
2021-02-16 18:29:43,677 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,677 main.py:78  ERROR Users can not have empty fields
2021-02-16 18:29:43,677 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,677 main.py:78  ERROR Users can not have empty fields
2021-02-16 18:29:43,677 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,677 main.py:78  ERROR Users can not have empty fields
2021-02-16 18:29:43,678 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,679 main.py:140 INFO Saving collection in database
2021-02-16 18:29:43,680 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 18:29:43,682 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,682 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:43,682 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,682 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:43,682 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,682 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:43,683 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,683 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:43,683 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,683 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:43,684 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,684 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 18:29:43,684 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,685 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 18:29:43,685 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,685 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 18:29:43,686 main.py:159 INFO Adding a new User
2021-02-16 18:29:43,687 main.py:171 INFO Updating an User
2021-02-16 18:29:43,689 main.py:184 INFO Deleting an User
2021-02-16 18:29:43,690 main.py:198 INFO Searching for an User
2021-02-16 18:29:43,691 main.py:198 INFO Searching for an User
2021-02-16 18:29:43,692 main.py:216 INFO Adding an UserStatus
2021-02-16 18:29:43,693 main.py:228 INFO Updating an UserStatus
2021-02-16 18:29:43,695 main.py:240 INFO Deleting an UserStatus
2021-02-16 18:29:43,696 main.py:253 INFO Searching for an UserStatus
2021-02-16 18:29:43,697 main.py:253 INFO Searching for an UserStatus
2021-02-16 18:29:43,698 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:29:43,748 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:43,749 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:29:43,815 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:43,815 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:43,816 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 18:29:43,816 main.py:159 INFO Adding a new User
2021-02-16 18:29:43,849 users.py:51  INFO User dave03 sucessfully added
2021-02-16 18:29:43,849 main.py:159 INFO Adding a new User
2021-02-16 18:29:43,849 users.py:49  ERROR User dave03 breaks database rule: UNIQUE constraint failed: user.user_id
2021-02-16 18:29:43,849 main.py:171 INFO Updating an User
2021-02-16 18:29:43,883 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 18:29:43,883 main.py:171 INFO Updating an User
2021-02-16 18:29:43,884 users.py:61  ERROR User dave02 not found in database
2021-02-16 18:29:43,884 main.py:198 INFO Searching for an User
2021-02-16 18:29:43,884 users.py:93  INFO User dave03 sucessfully found
2021-02-16 18:29:43,884 main.py:198 INFO Searching for an User
2021-02-16 18:29:43,885 users.py:91  ERROR User dave02 not found in database
2021-02-16 18:29:43,885 main.py:184 INFO Deleting an User
2021-02-16 18:29:43,917 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 18:29:43,917 main.py:184 INFO Deleting an User
2021-02-16 18:29:43,918 users.py:78  ERROR User dave03 not found in database
2021-02-16 18:29:43,918 main.py:159 INFO Adding a new User
2021-02-16 18:29:43,950 users.py:51  INFO User dave03 sucessfully added
2021-02-16 18:29:43,950 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:43,950 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 18:29:43,950 main.py:216 INFO Adding an UserStatus
2021-02-16 18:29:43,984 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 18:29:43,984 main.py:216 INFO Adding an UserStatus
2021-02-16 18:29:43,984 user_status.py:48  ERROR Status dave03_01 breaks database rule: UNIQUE constraint failed: status.status_id
2021-02-16 18:29:43,984 main.py:228 INFO Updating an UserStatus
2021-02-16 18:29:44,018 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 18:29:44,018 main.py:228 INFO Updating an UserStatus
2021-02-16 18:29:44,018 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 18:29:44,018 main.py:253 INFO Searching for an UserStatus
2021-02-16 18:29:44,019 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 18:29:44,019 main.py:253 INFO Searching for an UserStatus
2021-02-16 18:29:44,020 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 18:29:44,020 main.py:240 INFO Deleting an UserStatus
2021-02-16 18:29:44,051 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 18:29:44,051 main.py:240 INFO Deleting an UserStatus
2021-02-16 18:29:44,052 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 18:29:44,053 user_status.py:20  INFO Status rando_001 created
2021-02-16 18:29:44,055 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:44,057 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:44,059 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 18:29:44,065 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:44,066 user_status.py:48  ERROR Status rando_001 breaks database rule: 
2021-02-16 18:29:44,067 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:44,068 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 18:29:44,069 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:44,070 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 18:29:44,071 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:44,071 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 18:29:44,073 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:44,073 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 18:29:44,075 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:44,075 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 18:29:44,076 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:44,077 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 18:29:44,078 users.py:21  INFO User rando created
2021-02-16 18:29:44,079 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:44,080 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:44,081 users.py:51  INFO User rando sucessfully added
2021-02-16 18:29:44,082 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:44,084 users.py:49  ERROR User rando breaks database rule: 
2021-02-16 18:29:44,085 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:44,086 users.py:68  INFO User rando sucessfully modified
2021-02-16 18:29:44,087 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:44,087 users.py:61  ERROR User rando not found in database
2021-02-16 18:29:44,088 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:44,089 users.py:81  INFO User rando sucessfully deleted
2021-02-16 18:29:44,090 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:44,090 users.py:78  ERROR User rando not found in database
2021-02-16 18:29:44,091 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:44,092 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='2497745958984'> sucessfully found
2021-02-16 18:29:44,093 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:44,094 users.py:91  ERROR User rando not found in database
2021-02-16 18:29:47,953 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:29:47,955 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:29:47,957 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,957 main.py:86  INFO Saving collection in database
2021-02-16 18:29:47,959 main.py:60  ERROR User files must be in csv format
2021-02-16 18:29:47,961 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,961 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:47,961 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,962 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:47,962 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,962 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:47,962 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,962 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:47,963 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,963 main.py:73  ERROR Users need four parameters
2021-02-16 18:29:47,964 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,964 main.py:78  ERROR Users can not have empty fields
2021-02-16 18:29:47,965 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,965 main.py:78  ERROR Users can not have empty fields
2021-02-16 18:29:47,965 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,965 main.py:78  ERROR Users can not have empty fields
2021-02-16 18:29:47,965 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:47,965 main.py:78  ERROR Users can not have empty fields
2021-02-16 18:29:47,967 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:47,967 main.py:140 INFO Saving collection in database
2021-02-16 18:29:47,970 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 18:29:47,972 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:47,972 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:47,972 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:47,972 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:47,973 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:47,973 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:47,973 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:47,973 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:47,973 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:47,973 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 18:29:47,975 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:47,975 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 18:29:47,975 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:47,976 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 18:29:47,976 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:47,976 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 18:29:47,977 main.py:159 INFO Adding a new User
2021-02-16 18:29:47,979 main.py:171 INFO Updating an User
2021-02-16 18:29:47,981 main.py:184 INFO Deleting an User
2021-02-16 18:29:47,982 main.py:198 INFO Searching for an User
2021-02-16 18:29:47,984 main.py:198 INFO Searching for an User
2021-02-16 18:29:47,985 main.py:216 INFO Adding an UserStatus
2021-02-16 18:29:47,987 main.py:228 INFO Updating an UserStatus
2021-02-16 18:29:47,989 main.py:240 INFO Deleting an UserStatus
2021-02-16 18:29:47,990 main.py:253 INFO Searching for an UserStatus
2021-02-16 18:29:47,992 main.py:253 INFO Searching for an UserStatus
2021-02-16 18:29:47,994 main.py:28  INFO Creating a new UserCollection
2021-02-16 18:29:48,064 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,064 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 18:29:48,131 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,131 main.py:63  INFO Loading users from accounts.csv
2021-02-16 18:29:48,131 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 18:29:48,131 main.py:159 INFO Adding a new User
2021-02-16 18:29:48,175 users.py:51  INFO User dave03 sucessfully added
2021-02-16 18:29:48,176 main.py:159 INFO Adding a new User
2021-02-16 18:29:48,176 users.py:49  ERROR User dave03 breaks database rule: UNIQUE constraint failed: user.user_id
2021-02-16 18:29:48,176 main.py:171 INFO Updating an User
2021-02-16 18:29:48,220 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 18:29:48,220 main.py:171 INFO Updating an User
2021-02-16 18:29:48,221 users.py:61  ERROR User dave02 not found in database
2021-02-16 18:29:48,221 main.py:198 INFO Searching for an User
2021-02-16 18:29:48,222 users.py:93  INFO User dave03 sucessfully found
2021-02-16 18:29:48,222 main.py:198 INFO Searching for an User
2021-02-16 18:29:48,223 users.py:91  ERROR User dave02 not found in database
2021-02-16 18:29:48,223 main.py:184 INFO Deleting an User
2021-02-16 18:29:48,254 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 18:29:48,254 main.py:184 INFO Deleting an User
2021-02-16 18:29:48,255 users.py:78  ERROR User dave03 not found in database
2021-02-16 18:29:48,255 main.py:159 INFO Adding a new User
2021-02-16 18:29:48,287 users.py:51  INFO User dave03 sucessfully added
2021-02-16 18:29:48,288 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 18:29:48,288 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 18:29:48,288 main.py:216 INFO Adding an UserStatus
2021-02-16 18:29:48,321 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 18:29:48,321 main.py:216 INFO Adding an UserStatus
2021-02-16 18:29:48,322 user_status.py:48  ERROR Status dave03_01 breaks database rule: UNIQUE constraint failed: status.status_id
2021-02-16 18:29:48,322 main.py:228 INFO Updating an UserStatus
2021-02-16 18:29:48,355 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 18:29:48,355 main.py:228 INFO Updating an UserStatus
2021-02-16 18:29:48,356 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 18:29:48,356 main.py:253 INFO Searching for an UserStatus
2021-02-16 18:29:48,357 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 18:29:48,358 main.py:253 INFO Searching for an UserStatus
2021-02-16 18:29:48,359 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 18:29:48,359 main.py:240 INFO Deleting an UserStatus
2021-02-16 18:29:48,389 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 18:29:48,389 main.py:240 INFO Deleting an UserStatus
2021-02-16 18:29:48,389 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 18:29:48,391 user_status.py:20  INFO Status rando_001 created
2021-02-16 18:29:48,393 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,395 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,397 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 18:29:48,398 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,400 user_status.py:48  ERROR Status rando_001 breaks database rule: 
2021-02-16 18:29:48,401 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,403 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 18:29:48,405 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,405 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 18:29:48,407 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,408 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 18:29:48,410 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,410 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 18:29:48,412 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,413 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 18:29:48,414 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 18:29:48,415 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 18:29:48,417 users.py:21  INFO User rando created
2021-02-16 18:29:48,419 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,420 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,422 users.py:51  INFO User rando sucessfully added
2021-02-16 18:29:48,423 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,424 users.py:49  ERROR User rando breaks database rule: 
2021-02-16 18:29:48,426 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,427 users.py:68  INFO User rando sucessfully modified
2021-02-16 18:29:48,429 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,430 users.py:61  ERROR User rando not found in database
2021-02-16 18:29:48,431 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,432 users.py:81  INFO User rando sucessfully deleted
2021-02-16 18:29:48,434 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,434 users.py:78  ERROR User rando not found in database
2021-02-16 18:29:48,436 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,436 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='2614711047048'> sucessfully found
2021-02-16 18:29:48,438 users.py:33  INFO New UserCollection instance created
2021-02-16 18:29:48,438 users.py:91  ERROR User rando not found in database
2021-02-16 19:06:07,977 main.py:28  INFO Creating a new UserCollection
2021-02-16 19:06:07,979 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 19:06:07,981 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,981 main.py:86  INFO Saving collection in database
2021-02-16 19:06:07,984 main.py:60  ERROR User files must be in csv format
2021-02-16 19:06:07,985 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,985 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:07,986 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,986 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:07,986 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,986 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:07,986 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,986 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:07,987 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,987 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:07,988 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,989 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:06:07,989 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,989 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:06:07,989 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,989 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:06:07,989 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:07,989 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:06:07,991 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:07,991 main.py:140 INFO Saving collection in database
2021-02-16 19:06:07,994 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 19:06:07,996 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:07,996 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:07,996 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:07,996 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:07,997 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:07,997 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:07,997 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:07,997 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:07,997 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:07,997 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:07,999 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:07,999 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:06:07,999 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:08,000 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:06:08,000 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:08,000 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:06:08,001 main.py:159 INFO Adding a new User
2021-02-16 19:06:08,003 main.py:171 INFO Updating an User
2021-02-16 19:06:08,005 main.py:184 INFO Deleting an User
2021-02-16 19:06:08,006 main.py:198 INFO Searching for an User
2021-02-16 19:06:08,008 main.py:198 INFO Searching for an User
2021-02-16 19:06:08,010 main.py:216 INFO Adding an UserStatus
2021-02-16 19:06:08,011 main.py:228 INFO Updating an UserStatus
2021-02-16 19:06:08,013 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:06:08,015 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:08,016 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:08,024 main.py:28  INFO Creating a new UserCollection
2021-02-16 19:06:08,074 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,074 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 19:06:08,141 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,141 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:08,141 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 19:06:08,141 main.py:159 INFO Adding a new User
2021-02-16 19:06:08,174 users.py:51  INFO User dave03 sucessfully added
2021-02-16 19:06:08,174 main.py:159 INFO Adding a new User
2021-02-16 19:06:08,175 users.py:49  ERROR User dave03 breaks database rule: UNIQUE constraint failed: user.user_id
2021-02-16 19:06:08,175 main.py:171 INFO Updating an User
2021-02-16 19:06:08,208 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 19:06:08,208 main.py:171 INFO Updating an User
2021-02-16 19:06:08,209 users.py:61  ERROR User dave02 not found in database
2021-02-16 19:06:08,209 main.py:198 INFO Searching for an User
2021-02-16 19:06:08,210 users.py:93  INFO User dave03 sucessfully found
2021-02-16 19:06:08,210 main.py:198 INFO Searching for an User
2021-02-16 19:06:08,211 users.py:91  ERROR User dave02 not found in database
2021-02-16 19:06:08,211 main.py:184 INFO Deleting an User
2021-02-16 19:06:08,242 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 19:06:08,242 main.py:184 INFO Deleting an User
2021-02-16 19:06:08,243 users.py:78  ERROR User dave03 not found in database
2021-02-16 19:06:08,243 main.py:159 INFO Adding a new User
2021-02-16 19:06:08,275 users.py:51  INFO User dave03 sucessfully added
2021-02-16 19:06:08,276 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:08,276 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 19:06:08,276 main.py:216 INFO Adding an UserStatus
2021-02-16 19:06:08,309 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 19:06:08,309 main.py:216 INFO Adding an UserStatus
2021-02-16 19:06:08,310 user_status.py:48  ERROR Status dave03_01 breaks database rule: UNIQUE constraint failed: status.status_id
2021-02-16 19:06:08,310 main.py:228 INFO Updating an UserStatus
2021-02-16 19:06:08,343 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 19:06:08,343 main.py:228 INFO Updating an UserStatus
2021-02-16 19:06:08,344 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 19:06:08,344 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:08,345 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 19:06:08,345 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:08,346 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 19:06:08,346 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:06:08,376 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 19:06:08,377 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:06:08,377 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 19:06:08,378 main.py:216 INFO Adding an UserStatus
2021-02-16 19:06:08,410 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 19:06:08,410 main.py:184 INFO Deleting an User
2021-02-16 19:06:08,444 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 19:06:08,444 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:08,445 user_status.py:92  ERROR Status dave03_01 not found database
2021-02-16 19:06:08,445 main.py:159 INFO Adding a new User
2021-02-16 19:06:08,446 users.py:49  ERROR User ############################## breaks database rule: CHECK constraint failed: user
2021-02-16 19:06:08,446 main.py:159 INFO Adding a new User
2021-02-16 19:06:08,446 users.py:49  ERROR User name breaks database rule: CHECK constraint failed: user
2021-02-16 19:06:08,446 main.py:159 INFO Adding a new User
2021-02-16 19:06:08,447 users.py:49  ERROR User last_name breaks database rule: CHECK constraint failed: user
2021-02-16 19:06:08,449 user_status.py:20  INFO Status rando_001 created
2021-02-16 19:06:08,451 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,453 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,454 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 19:06:08,456 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,457 user_status.py:48  ERROR Status rando_001 breaks database rule: 
2021-02-16 19:06:08,459 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,461 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 19:06:08,462 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,463 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 19:06:08,465 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,465 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 19:06:08,467 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,468 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 19:06:08,470 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,470 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 19:06:08,472 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:08,473 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 19:06:08,475 users.py:21  INFO User rando created
2021-02-16 19:06:08,476 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,478 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,479 users.py:51  INFO User rando sucessfully added
2021-02-16 19:06:08,481 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,482 users.py:49  ERROR User rando breaks database rule: 
2021-02-16 19:06:08,484 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,485 users.py:68  INFO User rando sucessfully modified
2021-02-16 19:06:08,487 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,488 users.py:61  ERROR User rando not found in database
2021-02-16 19:06:08,489 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,490 users.py:81  INFO User rando sucessfully deleted
2021-02-16 19:06:08,491 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,492 users.py:78  ERROR User rando not found in database
2021-02-16 19:06:08,494 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,494 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='2072470926600'> sucessfully found
2021-02-16 19:06:08,496 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:08,496 users.py:91  ERROR User rando not found in database
2021-02-16 19:06:12,914 main.py:28  INFO Creating a new UserCollection
2021-02-16 19:06:12,916 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 19:06:12,918 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,918 main.py:86  INFO Saving collection in database
2021-02-16 19:06:12,921 main.py:60  ERROR User files must be in csv format
2021-02-16 19:06:12,923 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,923 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:12,923 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,923 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:12,923 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,923 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:12,924 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,924 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:12,924 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,924 main.py:73  ERROR Users need four parameters
2021-02-16 19:06:12,926 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,926 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:06:12,926 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,926 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:06:12,926 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,926 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:06:12,927 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:12,927 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:06:12,929 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:12,929 main.py:140 INFO Saving collection in database
2021-02-16 19:06:12,932 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 19:06:12,933 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:12,933 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:12,934 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:12,934 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:12,934 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:12,934 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:12,934 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:12,934 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:12,935 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:12,935 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:06:12,936 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:12,937 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:06:12,937 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:12,937 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:06:12,937 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:12,937 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:06:12,939 main.py:159 INFO Adding a new User
2021-02-16 19:06:12,940 main.py:171 INFO Updating an User
2021-02-16 19:06:12,942 main.py:184 INFO Deleting an User
2021-02-16 19:06:12,944 main.py:198 INFO Searching for an User
2021-02-16 19:06:12,945 main.py:198 INFO Searching for an User
2021-02-16 19:06:12,947 main.py:216 INFO Adding an UserStatus
2021-02-16 19:06:12,949 main.py:228 INFO Updating an UserStatus
2021-02-16 19:06:12,950 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:06:12,952 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:12,954 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:12,956 main.py:28  INFO Creating a new UserCollection
2021-02-16 19:06:13,022 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,022 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 19:06:13,089 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,090 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:06:13,090 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 19:06:13,090 main.py:159 INFO Adding a new User
2021-02-16 19:06:13,134 users.py:51  INFO User dave03 sucessfully added
2021-02-16 19:06:13,135 main.py:159 INFO Adding a new User
2021-02-16 19:06:13,135 users.py:49  ERROR User dave03 breaks database rule: UNIQUE constraint failed: user.user_id
2021-02-16 19:06:13,135 main.py:171 INFO Updating an User
2021-02-16 19:06:13,168 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 19:06:13,168 main.py:171 INFO Updating an User
2021-02-16 19:06:13,169 users.py:61  ERROR User dave02 not found in database
2021-02-16 19:06:13,169 main.py:198 INFO Searching for an User
2021-02-16 19:06:13,169 users.py:93  INFO User dave03 sucessfully found
2021-02-16 19:06:13,169 main.py:198 INFO Searching for an User
2021-02-16 19:06:13,170 users.py:91  ERROR User dave02 not found in database
2021-02-16 19:06:13,170 main.py:184 INFO Deleting an User
2021-02-16 19:06:13,201 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 19:06:13,201 main.py:184 INFO Deleting an User
2021-02-16 19:06:13,202 users.py:78  ERROR User dave03 not found in database
2021-02-16 19:06:13,202 main.py:159 INFO Adding a new User
2021-02-16 19:06:13,236 users.py:51  INFO User dave03 sucessfully added
2021-02-16 19:06:13,236 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:06:13,236 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 19:06:13,236 main.py:216 INFO Adding an UserStatus
2021-02-16 19:06:13,269 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 19:06:13,269 main.py:216 INFO Adding an UserStatus
2021-02-16 19:06:13,270 user_status.py:48  ERROR Status dave03_01 breaks database rule: UNIQUE constraint failed: status.status_id
2021-02-16 19:06:13,270 main.py:228 INFO Updating an UserStatus
2021-02-16 19:06:13,303 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 19:06:13,303 main.py:228 INFO Updating an UserStatus
2021-02-16 19:06:13,304 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 19:06:13,304 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:13,304 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 19:06:13,305 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:13,306 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 19:06:13,306 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:06:13,336 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 19:06:13,336 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:06:13,337 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 19:06:13,337 main.py:216 INFO Adding an UserStatus
2021-02-16 19:06:13,370 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 19:06:13,370 main.py:184 INFO Deleting an User
2021-02-16 19:06:13,404 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 19:06:13,404 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:06:13,405 user_status.py:92  ERROR Status dave03_01 not found database
2021-02-16 19:06:13,405 main.py:159 INFO Adding a new User
2021-02-16 19:06:13,406 users.py:49  ERROR User ############################## breaks database rule: CHECK constraint failed: user
2021-02-16 19:06:13,406 main.py:159 INFO Adding a new User
2021-02-16 19:06:13,406 users.py:49  ERROR User name breaks database rule: CHECK constraint failed: user
2021-02-16 19:06:13,406 main.py:159 INFO Adding a new User
2021-02-16 19:06:13,407 users.py:49  ERROR User last_name breaks database rule: CHECK constraint failed: user
2021-02-16 19:06:13,409 user_status.py:20  INFO Status rando_001 created
2021-02-16 19:06:13,412 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,414 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,415 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 19:06:13,417 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,418 user_status.py:48  ERROR Status rando_001 breaks database rule: 
2021-02-16 19:06:13,420 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,422 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 19:06:13,423 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,424 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 19:06:13,426 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,426 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 19:06:13,428 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,429 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 19:06:13,430 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,431 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 19:06:13,433 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:06:13,434 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 19:06:13,436 users.py:21  INFO User rando created
2021-02-16 19:06:13,437 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,439 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,440 users.py:51  INFO User rando sucessfully added
2021-02-16 19:06:13,442 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,443 users.py:49  ERROR User rando breaks database rule: 
2021-02-16 19:06:13,444 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,446 users.py:68  INFO User rando sucessfully modified
2021-02-16 19:06:13,447 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,448 users.py:61  ERROR User rando not found in database
2021-02-16 19:06:13,450 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,451 users.py:81  INFO User rando sucessfully deleted
2021-02-16 19:06:13,452 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,453 users.py:78  ERROR User rando not found in database
2021-02-16 19:06:13,454 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,455 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='2550172548232'> sucessfully found
2021-02-16 19:06:13,457 users.py:33  INFO New UserCollection instance created
2021-02-16 19:06:13,457 users.py:91  ERROR User rando not found in database
2021-02-16 19:16:11,303 main.py:28  INFO Creating a new UserCollection
2021-02-16 19:16:11,305 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 19:16:11,307 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,307 main.py:86  INFO Saving collection in database
2021-02-16 19:16:11,310 main.py:60  ERROR User files must be in csv format
2021-02-16 19:16:11,312 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,312 main.py:73  ERROR Users need four parameters
2021-02-16 19:16:11,312 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,312 main.py:73  ERROR Users need four parameters
2021-02-16 19:16:11,313 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,313 main.py:73  ERROR Users need four parameters
2021-02-16 19:16:11,313 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,313 main.py:73  ERROR Users need four parameters
2021-02-16 19:16:11,313 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,313 main.py:73  ERROR Users need four parameters
2021-02-16 19:16:11,315 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,315 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:16:11,316 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,316 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:16:11,316 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,316 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:16:11,316 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,316 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:16:11,318 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,318 main.py:140 INFO Saving collection in database
2021-02-16 19:16:11,321 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 19:16:11,323 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,323 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:16:11,323 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,323 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:16:11,323 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,323 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:16:11,324 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,324 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:16:11,324 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,324 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:16:11,326 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,326 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:16:11,326 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,326 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:16:11,327 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,327 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:16:11,328 main.py:159 INFO Adding a new User
2021-02-16 19:16:11,330 main.py:171 INFO Updating an User
2021-02-16 19:16:11,337 main.py:184 INFO Deleting an User
2021-02-16 19:16:11,339 main.py:198 INFO Searching for an User
2021-02-16 19:16:11,341 main.py:198 INFO Searching for an User
2021-02-16 19:16:11,342 main.py:216 INFO Adding an UserStatus
2021-02-16 19:16:11,344 main.py:228 INFO Updating an UserStatus
2021-02-16 19:16:11,346 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:16:11,348 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:16:11,349 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:16:11,351 main.py:28  INFO Creating a new UserCollection
2021-02-16 19:16:11,404 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,404 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 19:16:11,482 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,482 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:16:11,482 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 19:16:11,483 main.py:159 INFO Adding a new User
2021-02-16 19:16:11,515 users.py:51  INFO User dave03 sucessfully added
2021-02-16 19:16:11,516 main.py:159 INFO Adding a new User
2021-02-16 19:16:11,516 users.py:49  ERROR User dave03 breaks database rule: UNIQUE constraint failed: user.user_id
2021-02-16 19:16:11,517 main.py:171 INFO Updating an User
2021-02-16 19:16:11,549 users.py:68  INFO User dave03 sucessfully modified
2021-02-16 19:16:11,549 main.py:171 INFO Updating an User
2021-02-16 19:16:11,550 users.py:61  ERROR User dave02 not found in database
2021-02-16 19:16:11,550 main.py:198 INFO Searching for an User
2021-02-16 19:16:11,551 users.py:93  INFO User dave03 sucessfully found
2021-02-16 19:16:11,551 main.py:198 INFO Searching for an User
2021-02-16 19:16:11,552 users.py:91  ERROR User dave02 not found in database
2021-02-16 19:16:11,552 main.py:184 INFO Deleting an User
2021-02-16 19:16:11,583 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 19:16:11,583 main.py:184 INFO Deleting an User
2021-02-16 19:16:11,584 users.py:78  ERROR User dave03 not found in database
2021-02-16 19:16:11,584 main.py:159 INFO Adding a new User
2021-02-16 19:16:11,616 users.py:51  INFO User dave03 sucessfully added
2021-02-16 19:16:11,617 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:16:11,617 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 19:16:11,617 main.py:216 INFO Adding an UserStatus
2021-02-16 19:16:11,651 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 19:16:11,651 main.py:216 INFO Adding an UserStatus
2021-02-16 19:16:11,652 user_status.py:48  ERROR Status dave03_01 breaks database rule: UNIQUE constraint failed: status.status_id
2021-02-16 19:16:11,652 main.py:228 INFO Updating an UserStatus
2021-02-16 19:16:11,685 user_status.py:67  INFO Status dave03_01 sucessfully modified
2021-02-16 19:16:11,685 main.py:228 INFO Updating an UserStatus
2021-02-16 19:16:11,685 user_status.py:61  ERROR Status dave03_02 not found database
2021-02-16 19:16:11,686 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:16:11,686 user_status.py:94  INFO Status dave03_01 sucessfully found
2021-02-16 19:16:11,687 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:16:11,687 user_status.py:92  ERROR Status dave03 not found database
2021-02-16 19:16:11,687 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:16:11,718 user_status.py:81  INFO Status dave03_01 sucessfully deleted
2021-02-16 19:16:11,718 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:16:11,719 user_status.py:78  ERROR Status dave03_01 not found database
2021-02-16 19:16:11,719 main.py:216 INFO Adding an UserStatus
2021-02-16 19:16:11,752 user_status.py:50  INFO Status dave03_01 added to database
2021-02-16 19:16:11,752 main.py:184 INFO Deleting an User
2021-02-16 19:16:11,786 users.py:81  INFO User dave03 sucessfully deleted
2021-02-16 19:16:11,786 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:16:11,787 user_status.py:92  ERROR Status dave03_01 not found database
2021-02-16 19:16:11,787 main.py:159 INFO Adding a new User
2021-02-16 19:16:11,788 users.py:49  ERROR User ############################## breaks database rule: CHECK constraint failed: user
2021-02-16 19:16:11,788 main.py:159 INFO Adding a new User
2021-02-16 19:16:11,788 users.py:49  ERROR User name breaks database rule: CHECK constraint failed: user
2021-02-16 19:16:11,788 main.py:159 INFO Adding a new User
2021-02-16 19:16:11,789 users.py:49  ERROR User last_name breaks database rule: CHECK constraint failed: user
2021-02-16 19:16:11,791 user_status.py:20  INFO Status rando_001 created
2021-02-16 19:16:11,793 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,796 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,797 user_status.py:50  INFO Status rando_001 added to database
2021-02-16 19:16:11,799 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,800 user_status.py:48  ERROR Status rando_001 breaks database rule: 
2021-02-16 19:16:11,802 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,803 user_status.py:67  INFO Status rando_001 sucessfully modified
2021-02-16 19:16:11,805 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,806 user_status.py:61  ERROR Status rando_001 not found database
2021-02-16 19:16:11,807 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,809 user_status.py:81  INFO Status rando_001 sucessfully deleted
2021-02-16 19:16:11,810 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,811 user_status.py:78  ERROR Status rando_001 not found database
2021-02-16 19:16:11,813 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,813 user_status.py:94  INFO Status rando_001 sucessfully found
2021-02-16 19:16:11,815 user_status.py:33  INFO New UserStatusCollection instance created
2021-02-16 19:16:11,815 user_status.py:92  ERROR Status rando_001 not found database
2021-02-16 19:16:11,817 users.py:21  INFO User rando created
2021-02-16 19:16:11,819 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,820 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,822 users.py:51  INFO User rando sucessfully added
2021-02-16 19:16:11,824 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,825 users.py:49  ERROR User rando breaks database rule: 
2021-02-16 19:16:11,827 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,828 users.py:68  INFO User rando sucessfully modified
2021-02-16 19:16:11,829 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,830 users.py:61  ERROR User rando not found in database
2021-02-16 19:16:11,831 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,832 users.py:81  INFO User rando sucessfully deleted
2021-02-16 19:16:11,834 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,834 users.py:78  ERROR User rando not found in database
2021-02-16 19:16:11,836 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,837 users.py:93  INFO User <Mock name='sql.User.get().user_id' id='2577506843208'> sucessfully found
2021-02-16 19:16:11,838 users.py:33  INFO New UserCollection instance created
2021-02-16 19:16:11,839 users.py:91  ERROR User rando not found in database
2021-02-16 19:38:26,492 main.py:28  INFO Creating a new UserCollection
2021-02-16 19:38:26,494 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 19:38:26,496 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,496 main.py:86  INFO Saving collection in database
2021-02-16 19:38:26,499 main.py:60  ERROR User files must be in csv format
2021-02-16 19:38:26,501 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,501 main.py:73  ERROR Users need four parameters
2021-02-16 19:38:26,501 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,501 main.py:73  ERROR Users need four parameters
2021-02-16 19:38:26,501 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,501 main.py:73  ERROR Users need four parameters
2021-02-16 19:38:26,502 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,502 main.py:73  ERROR Users need four parameters
2021-02-16 19:38:26,502 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,502 main.py:73  ERROR Users need four parameters
2021-02-16 19:38:26,504 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,504 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:38:26,504 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,504 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:38:26,505 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,505 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:38:26,505 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,505 main.py:78  ERROR Users can not have empty fields
2021-02-16 19:38:26,507 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,507 main.py:140 INFO Saving collection in database
2021-02-16 19:38:26,510 main.py:114 ERROR UserStatus files must be in csv format
2021-02-16 19:38:26,511 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,511 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:38:26,512 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,512 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:38:26,512 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,512 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:38:26,512 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,512 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:38:26,513 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,513 main.py:127 ERROR UserStatus needs three parameters
2021-02-16 19:38:26,515 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,515 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:38:26,515 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,515 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:38:26,516 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,516 main.py:132 ERROR UserStatus can not have empty fields
2021-02-16 19:38:26,517 main.py:159 INFO Adding a new User
2021-02-16 19:38:26,524 main.py:171 INFO Updating an User
2021-02-16 19:38:26,525 main.py:184 INFO Deleting an User
2021-02-16 19:38:26,527 main.py:198 INFO Searching for an User
2021-02-16 19:38:26,529 main.py:198 INFO Searching for an User
2021-02-16 19:38:26,530 main.py:216 INFO Adding an UserStatus
2021-02-16 19:38:26,532 main.py:228 INFO Updating an UserStatus
2021-02-16 19:38:26,534 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:38:26,535 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:38:26,537 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:38:26,538 main.py:28  INFO Creating a new UserCollection
2021-02-16 19:38:26,598 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:26,598 main.py:37  INFO Createing a new UserStatusCollection
2021-02-16 19:38:26,665 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,665 main.py:63  INFO Loading users from accounts.csv
2021-02-16 19:38:26,665 main.py:68  ERROR accounts.csv does not contain data
2021-02-16 19:38:26,665 main.py:159 INFO Adding a new User
2021-02-16 19:38:26,698 users.py:38  INFO User dave03 sucessfully added
2021-02-16 19:38:26,699 main.py:159 INFO Adding a new User
2021-02-16 19:38:26,699 users.py:36  ERROR User dave03 breaks database rule: UNIQUE constraint failed: user.user_id
2021-02-16 19:38:26,699 main.py:171 INFO Updating an User
2021-02-16 19:38:26,732 users.py:55  INFO User dave03 sucessfully modified
2021-02-16 19:38:26,732 main.py:171 INFO Updating an User
2021-02-16 19:38:26,733 users.py:48  ERROR User dave02 not found in database
2021-02-16 19:38:26,733 main.py:198 INFO Searching for an User
2021-02-16 19:38:26,734 users.py:80  INFO User dave03 sucessfully found
2021-02-16 19:38:26,734 main.py:198 INFO Searching for an User
2021-02-16 19:38:26,735 users.py:78  ERROR User dave02 not found in database
2021-02-16 19:38:26,735 main.py:184 INFO Deleting an User
2021-02-16 19:38:26,766 users.py:68  INFO User dave03 sucessfully deleted
2021-02-16 19:38:26,766 main.py:184 INFO Deleting an User
2021-02-16 19:38:26,767 users.py:65  ERROR User dave03 not found in database
2021-02-16 19:38:26,767 main.py:159 INFO Adding a new User
2021-02-16 19:38:26,799 users.py:38  INFO User dave03 sucessfully added
2021-02-16 19:38:26,800 main.py:117 INFO Saving statuses to status_updates.csv
2021-02-16 19:38:26,800 main.py:122 ERROR status_updates.csv does not contain data
2021-02-16 19:38:26,800 main.py:216 INFO Adding an UserStatus
2021-02-16 19:38:26,833 user_status.py:38  INFO Status dave03_01 added to database
2021-02-16 19:38:26,833 main.py:216 INFO Adding an UserStatus
2021-02-16 19:38:26,834 user_status.py:36  ERROR Status dave03_01 breaks database rule: UNIQUE constraint failed: status.status_id
2021-02-16 19:38:26,834 main.py:228 INFO Updating an UserStatus
2021-02-16 19:38:26,867 user_status.py:55  INFO Status dave03_01 sucessfully modified
2021-02-16 19:38:26,867 main.py:228 INFO Updating an UserStatus
2021-02-16 19:38:26,868 user_status.py:49  ERROR Status dave03_02 not found database
2021-02-16 19:38:26,868 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:38:26,869 user_status.py:82  INFO Status dave03_01 sucessfully found
2021-02-16 19:38:26,869 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:38:26,870 user_status.py:80  ERROR Status dave03 not found database
2021-02-16 19:38:26,870 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:38:26,900 user_status.py:69  INFO Status dave03_01 sucessfully deleted
2021-02-16 19:38:26,901 main.py:240 INFO Deleting an UserStatus
2021-02-16 19:38:26,901 user_status.py:66  ERROR Status dave03_01 not found database
2021-02-16 19:38:26,901 main.py:216 INFO Adding an UserStatus
2021-02-16 19:38:26,934 user_status.py:38  INFO Status dave03_01 added to database
2021-02-16 19:38:26,934 main.py:184 INFO Deleting an User
2021-02-16 19:38:26,968 users.py:68  INFO User dave03 sucessfully deleted
2021-02-16 19:38:26,968 main.py:253 INFO Searching for an UserStatus
2021-02-16 19:38:26,969 user_status.py:80  ERROR Status dave03_01 not found database
2021-02-16 19:38:26,969 main.py:159 INFO Adding a new User
2021-02-16 19:38:26,969 users.py:36  ERROR User ############################## breaks database rule: CHECK constraint failed: user
2021-02-16 19:38:26,970 main.py:159 INFO Adding a new User
2021-02-16 19:38:26,970 users.py:36  ERROR User name breaks database rule: CHECK constraint failed: user
2021-02-16 19:38:26,970 main.py:159 INFO Adding a new User
2021-02-16 19:38:26,971 users.py:36  ERROR User last_name breaks database rule: CHECK constraint failed: user
2021-02-16 19:38:26,974 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,977 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,978 user_status.py:38  INFO Status rando_001 added to database
2021-02-16 19:38:26,980 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,981 user_status.py:36  ERROR Status rando_001 breaks database rule: 
2021-02-16 19:38:26,983 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,984 user_status.py:55  INFO Status rando_001 sucessfully modified
2021-02-16 19:38:26,986 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,986 user_status.py:49  ERROR Status rando_001 not found database
2021-02-16 19:38:26,989 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,989 user_status.py:69  INFO Status rando_001 sucessfully deleted
2021-02-16 19:38:26,991 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,992 user_status.py:66  ERROR Status rando_001 not found database
2021-02-16 19:38:26,993 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,994 user_status.py:82  INFO Status rando_001 sucessfully found
2021-02-16 19:38:26,996 user_status.py:21  INFO New UserStatusCollection instance created
2021-02-16 19:38:26,996 user_status.py:80  ERROR Status rando_001 not found database
2021-02-16 19:38:26,999 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:27,000 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:27,002 users.py:38  INFO User rando sucessfully added
2021-02-16 19:38:27,003 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:27,005 users.py:36  ERROR User rando breaks database rule: 
2021-02-16 19:38:27,006 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:27,007 users.py:55  INFO User rando sucessfully modified
2021-02-16 19:38:27,009 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:27,010 users.py:48  ERROR User rando not found in database
2021-02-16 19:38:27,011 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:27,012 users.py:68  INFO User rando sucessfully deleted
2021-02-16 19:38:27,013 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:27,014 users.py:65  ERROR User rando not found in database
2021-02-16 19:38:27,016 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:27,017 users.py:80  INFO User <Mock name='sql.User.get().user_id' id='2409744345480'> sucessfully found
2021-02-16 19:38:27,018 users.py:20  INFO New UserCollection instance created
2021-02-16 19:38:27,019 users.py:78  ERROR User rando not found in database
